/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIPOS_H_RPCGEN
#define _TIPOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *Texto;

struct Persona {
	Texto nombre;
	int edad;
};
typedef struct Persona Persona;

struct Resultado {
	int caso;
	union {
		int n;
		float x;
		Texto error;
	} Resultado_u;
};
typedef struct Resultado Resultado;

struct Lista {
	int dato;
	struct Lista *siguiente;
};
typedef struct Lista Lista;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Texto (XDR *, Texto*);
extern  bool_t xdr_Persona (XDR *, Persona*);
extern  bool_t xdr_Resultado (XDR *, Resultado*);
extern  bool_t xdr_Lista (XDR *, Lista*);

#else /* K&R C */
extern bool_t xdr_Texto ();
extern bool_t xdr_Persona ();
extern bool_t xdr_Resultado ();
extern bool_t xdr_Lista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIPOS_H_RPCGEN */
