/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tipos.h"

bool_t
xdr_Texto (XDR *xdrs, Texto *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Persona (XDR *xdrs, Persona *objp)
{
	register int32_t *buf;

	 if (!xdr_Texto (xdrs, &objp->nombre))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->edad))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Resultado (XDR *xdrs, Resultado *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->caso))
		 return FALSE;
	switch (objp->caso) {
	case 1:
		 if (!xdr_int (xdrs, &objp->Resultado_u.n))
			 return FALSE;
		break;
	case 2:
		 if (!xdr_float (xdrs, &objp->Resultado_u.x))
			 return FALSE;
		break;
	case 3:
		 if (!xdr_Texto (xdrs, &objp->Resultado_u.error))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_Lista (XDR *xdrs, Lista *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dato))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (Lista), (xdrproc_t) xdr_Lista))
		 return FALSE;
	return TRUE;
}
